; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:lilygo-t-display-s3]
; platform = espressif32
; board = lilygo-t-display-s3
; framework = arduino    

; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001

; --- THE MAGIC LINE TO FIX THE CRASH ---
board_build.flash_mode = dio

[platformio]
description = Real-time microcomputer-based CO2 sensing technology to evaluate the CO2 adsorption efficiency of self-supporting zeolite-activated biochar composites by measuring the captured and released CO2 levels. The esp32dev environment is used for testing the flow of sensor data from microcontroller to MQTT broker.