# Generated by Django 5.2.18 on 2026-10-07 04:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValveSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(default='solenoid_valves', max_length=32, unique=True)),
                ('valves', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(choices=[('inlet', 'inlet'), ('outlet', 'outlet')], max_length=32)),
                ('message_id', models.CharField(blank=True, max_length=128, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('co2', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('flow_rate', models.FloatField(blank=True, null=True)),
                ('level', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('no2', models.FloatField(blank=True, null=True)),
                ('so2', models.FloatField(blank=True, null=True)),
                ('pressure1', models.FloatField(blank=True, null=True)),
                ('pressure2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['node_id', '-timestamp'], name='reading_node_time'), models.Index(fields=['-timestamp'], name='reading_time')],
                'constraints': [models.UniqueConstraint(fields=('node_id', 'message_id'), name='unique_node_message')],
            },
        ),
    ]
