# Generated by Django 5.2.18 on 2026-10-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=32, unique=True)),
                ('accepted', models.PositiveBigIntegerField(default=0)),
                ('duplicates', models.PositiveBigIntegerField(default=0)),
                ('conflicts', models.PositiveBigIntegerField(default=0)),
                ('invalid', models.PositiveBigIntegerField(default=0)),
                ('unauthorized', models.PositiveBigIntegerField(default=0)),
                ('server_errors', models.PositiveBigIntegerField(default=0)),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
                ('last_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_outcome', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
