# Generated by Django 5.2.18 on 2026-10-07 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_ingestionstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.SlugField(max_length=64, unique=True)),
                ('profile', models.CharField(choices=[('inlet', 'inlet'), ('outlet', 'outlet'), ('control', 'control')], max_length=16)),
                ('hardware', models.CharField(max_length=64)),
                ('credential_hash', models.CharField(editable=False, max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('approval_generation', models.PositiveBigIntegerField(default=0)),
                ('reported_version', models.CharField(blank=True, max_length=31)),
                ('reported_status', models.CharField(blank=True, max_length=32)),
                ('maintenance', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirmwareRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=31)),
                ('profile', models.CharField(choices=[('inlet', 'inlet'), ('outlet', 'outlet'), ('control', 'control')], max_length=16)),
                ('hardware', models.CharField(max_length=64)),
                ('manifest', models.TextField(help_text='Exact canonical signed JSON; do not reformat.')),
                ('signature', models.TextField(help_text='Base64 RSA-PSS manifest signature.')),
                ('base_url', models.URLField(help_text='HTTPS directory containing image and .bin.sig release assets.')),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('version', 'profile', 'hardware'), name='unique_firmware_release')],
            },
        ),
        migrations.CreateModel(
            name='FirmwareApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoring.device')),
                ('release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='monitoring.firmwarerelease')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='desired_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='monitoring.firmwarerelease'),
        ),
    ]
