[platformio]
default_envs = dev

[env]
platform = espressif32
framework = arduino
board = esp32dev
monitor_speed = 115200
upload_speed = 115200
upload_protocol = esptool

lib_deps =
    bblanchon/ArduinoJson
    knolleary/PubSubClient

build_flags =
    -D MQTT_MAX_PACKET_SIZE=1024
    -D SERIAL_BAUD=115200
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=0

check_tool =
    cppcheck
    clangtidy

check_skip_packages = yes

check_flags =
    cppcheck: --enable=warning,style,performance,portability --inline-suppr

[env:dev]
build_type = debug
build_flags =
    ${env.build_flags}
    -D FW_ENV=\"dev\"
    -D FW_VERSION=\"0.1.0-dev\"

[env:prod]
build_type = release
build_flags =
    ${env.build_flags}
    -D FW_ENV=\"prod\"
    -D FW_VERSION=\"0.1.0\"
board_build.partitions = partitions_ota.csv

[env:native]
platform = native
test_framework = unity
lib_deps =
    bblanchon/ArduinoJson