[platformio]
default_envs = inlet

[env]
platform = espressif32@7.0.1
platform_packages = framework-espidf@4.60001.0
framework = espidf
board = esp32dev
board_build.flash_size = 4MB
board_build.partitions = partitions_ota.csv
board_build.sdkconfig_defaults = sdkconfig.defaults
monitor_speed = 115200
upload_speed = 460800
upload_protocol = esptool
build_flags =
    -D ZC_HARDWARE=\"wroom32-4mb-v1\"

[env:inlet]
build_flags =
    ${env.build_flags}
    -D ZC_PROFILE=\"inlet\"

[env:outlet]
build_flags =
    ${env.build_flags}
    -D ZC_PROFILE=\"outlet\"

[env:control]
build_flags =
    ${env.build_flags}
    -D ZC_PROFILE=\"control\"
